version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
  build:
    commands:
      - echo start deploying
      - npx sls deploy
      - echo end deploying
  post_build:
    commands:
      - echo Deployment completed on `date`
