service: anki-twitter-bot

custom:
  bucketName: anki-bucket
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource:
        - arn:aws:s3:::anki-bucket/*
  environment:
    BUCKET_NAME: ${self:custom.bucketName}
    DECK_KEY: ${env:DECK_KEY}
    TWITTER_API_KEY: ${env:TWITTER_API_KEY}
    TWITTER_SECRET_KEY: ${env:TWITTER_SECRET_KEY}
    TWITTER_ACCESS_TOKEN: ${env:TWITTER_ACCESS_TOKEN}
    TWITTER_ACCESS_TOKEN_SECRET: ${env:TWITTER_ACCESS_TOKEN_SECRET}

functions:
  tweetAnki:
    handler: src/index.main
    events:
      - schedule: rate(6 hours)

resources:
  Resources:
    AnkiBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:custom.bucketName}
  Outputs:
    BucketUrl:
      Description: Anki Bucket URL
      Value: !Sub https://s3.console.aws.amazon.com/s3/buckets/${self:custom.bucketName}
